services:
  php7.2-apache:
    container_name: php7.2-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./sites:/var/www/html
    networks:
      network:
        ipv4_address: 10.5.0.5
    build:
      context: ./apache/php7.2

  php8.3-apache:
    image: php:8.3-apache
    container_name: php8.3-apache
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./sites:/var/www/html
      - ./apache/php8.3:/etc/apache2/sites-available
    networks:
      network:
        ipv4_address: 10.5.0.6

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
